// This file has been generated by the reflectable package.
// https://github.com/dart-lang/reflectable.

import 'dart:core';
import 'package:Elul/models/routineModel.dart' as prefix1;
import 'package:dart_json_mapper/src/model/annotations.dart' as prefix0;
import 'package:flutter/src/material/time.dart' as prefix3;
import 'package:mobx/src/api/annotations.dart' as prefix2;

// ignore_for_file: prefer_adjacent_string_concatenation
// ignore_for_file: prefer_collection_literals
// ignore_for_file: unnecessary_const
// ignore_for_file: implementation_imports

// ignore:unused_import
import 'package:reflectable/mirrors.dart' as m;
// ignore:unused_import
import 'package:reflectable/src/reflectable_builder_based.dart' as r;
// ignore:unused_import
import 'package:reflectable/reflectable.dart' as r show Reflectable;

final _data = <r.Reflectable, r.ReflectorData>{
  const prefix0.JsonSerializable(): r.ReflectorData(
      <m.TypeMirror>[
        r.NonGenericClassMirrorImpl(
            r'RoutineModel',
            r'.RoutineModel',
            7,
            0,
            const prefix0.JsonSerializable(),
            const <int>[5, 6, 7],
            const <int>[
              8,
              9,
              10,
              11,
              12,
              13,
              14,
              15,
              16,
              17,
              18,
              19,
              20,
              21,
              22,
              5
            ],
            const <int>[],
            -1,
            {},
            {},
            {
              r'': (b) => ({id, title, days, startTime, endTime}) => b
                  ? prefix1.RoutineModel(
                      days: days,
                      endTime: endTime,
                      id: id,
                      startTime: startTime,
                      title: title)
                  : null,
              r'fromJson': (b) =>
                  (json) => b ? prefix1.RoutineModel.fromJson(json) : null
            },
            -1,
            0,
            const <int>[],
            const <Object>[prefix0.jsonSerializable],
            null)
      ],
      <m.DeclarationMirror>[
        r.VariableMirrorImpl(
            r'id',
            32773,
            null,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1, const <int>[], const []),
        r.VariableMirrorImpl(
            r'title',
            32773,
            null,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const <Object>[prefix2.observable]),
        r.VariableMirrorImpl(
            r'days',
            2129925,
            null,
            const prefix0.JsonSerializable(),
            -1,
            3,
            4,
            null,
            const <Object>[prefix2.observable]),
        r.VariableMirrorImpl(
            r'startTime',
            32773,
            null,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const <Object>[prefix2.observable]),
        r.VariableMirrorImpl(
            r'endTime',
            32773,
            null,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const <Object>[prefix2.observable]),
        r.MethodMirrorImpl(r'toJson', 4325378, 0, -1, 6, 7, null, const <int>[],
            const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'',
            0,
            0,
            -1,
            0,
            0,
            const <int>[],
            const <int>[0, 1, 2, 3, 4],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'fromJson', 1, 0, -1, 0, 0, const <int>[],
            const <int>[5], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'==', 131074, null, -1, 8, 8, const <int>[],
            const <int>[6], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(r'toString', 131074, null, -1, 2, 2, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'noSuchMethod',
            65538,
            null,
            null,
            null,
            null,
            const <int>[],
            const <int>[7],
            const prefix0.JsonSerializable(),
            const []),
        r.MethodMirrorImpl(r'hashCode', 131075, null, -1, 1, 1, const <int>[],
            const <int>[], const prefix0.JsonSerializable(), const []),
        r.MethodMirrorImpl(
            r'runtimeType',
            131075,
            null,
            -1,
            9,
            9,
            const <int>[],
            const <int>[],
            const prefix0.JsonSerializable(),
            const []),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 0, 13),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 0, 14),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 1, 15),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 1, 16),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 2, 17),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 2, 18),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 3, 19),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 3, 20),
        r.ImplicitGetterMirrorImpl(const prefix0.JsonSerializable(), 4, 21),
        r.ImplicitSetterMirrorImpl(const prefix0.JsonSerializable(), 4, 22)
      ],
      <m.ParameterMirror>[
        r.ParameterMirrorImpl(r'id', 45062, 6, const prefix0.JsonSerializable(),
            -1, 1, 1, const <int>[], const [], null, #id),
        r.ParameterMirrorImpl(
            r'title',
            45062,
            6,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            #title),
        r.ParameterMirrorImpl(
            r'days',
            2142214,
            6,
            const prefix0.JsonSerializable(),
            -1,
            3,
            4,
            null,
            const [],
            null,
            #days),
        r.ParameterMirrorImpl(
            r'startTime',
            45062,
            6,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            #startTime),
        r.ParameterMirrorImpl(
            r'endTime',
            45062,
            6,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            #endTime),
        r.ParameterMirrorImpl(
            r'json',
            2129926,
            7,
            const prefix0.JsonSerializable(),
            -1,
            6,
            7,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'other',
            16390,
            8,
            const prefix0.JsonSerializable(),
            null,
            null,
            null,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'invocation',
            32774,
            10,
            const prefix0.JsonSerializable(),
            -1,
            10,
            10,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_id',
            32870,
            14,
            const prefix0.JsonSerializable(),
            -1,
            1,
            1,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_title',
            32870,
            16,
            const prefix0.JsonSerializable(),
            -1,
            2,
            2,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_days',
            2130022,
            18,
            const prefix0.JsonSerializable(),
            -1,
            3,
            4,
            null,
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_startTime',
            32870,
            20,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null),
        r.ParameterMirrorImpl(
            r'_endTime',
            32870,
            22,
            const prefix0.JsonSerializable(),
            -1,
            5,
            5,
            const <int>[],
            const [],
            null,
            null)
      ],
      <Type>[
        prefix1.RoutineModel,
        int,
        String,
        const m.TypeValue<List<dynamic>>().type,
        List,
        prefix3.TimeOfDay,
        const m.TypeValue<Map<String, dynamic>>().type,
        Map,
        bool,
        Type,
        Invocation
      ],
      1,
      {
        r'==': (dynamic instance) => (x) => instance == x,
        r'toString': (dynamic instance) => instance.toString,
        r'noSuchMethod': (dynamic instance) => instance.noSuchMethod,
        r'hashCode': (dynamic instance) => instance.hashCode,
        r'runtimeType': (dynamic instance) => instance.runtimeType,
        r'id': (dynamic instance) => instance.id,
        r'title': (dynamic instance) => instance.title,
        r'days': (dynamic instance) => instance.days,
        r'startTime': (dynamic instance) => instance.startTime,
        r'endTime': (dynamic instance) => instance.endTime,
        r'toJson': (dynamic instance) => instance.toJson
      },
      {
        r'id=': (dynamic instance, value) => instance.id = value,
        r'title=': (dynamic instance, value) => instance.title = value,
        r'days=': (dynamic instance, value) => instance.days = value,
        r'startTime=': (dynamic instance, value) => instance.startTime = value,
        r'endTime=': (dynamic instance, value) => instance.endTime = value
      },
      null,
      [])
};

final _memberSymbolMap = null;

void initializeReflectable() {
  r.data = _data;
  r.memberSymbolMap = _memberSymbolMap;
}
