name: Elul
description: A new routine app.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  #pega path da aplicacao
  path_provider: ^1.6.8
  #banco de dados noSql
  hive: ^1.4.1+1
  #provider e shared para implementar dark/light theme
  provider: ^4.0.5
  shared_preferences: ^0.5.6+3
  #mobX como gerenciador de estados
  flutter_mobx: ^1.0.0
  mobx: ^1.2.0
  #nao sei ora que serve ao certo ainda
  dio: ^3.0.4
  rxdart: ^0.22.6
  bloc_pattern: ^2.5.0
  #para as fontes utilizadas
  google_fonts: "^1.1.0"
  #para pegar a data e o horario
  intl: "^0.16.0"
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.7.2
  mobx_codegen: ^1.0.0
  mockito: ^4.1.1
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  fonts:
    - family: Lato
      fonts:
        - asset: fonts/Lato/Lato-Black.ttf
        - asset: fonts/Lato/Lato-Bold.ttf
        - asset: fonts/Lato/Lato-Regular.ttf
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans/OpenSans-Bold.ttf
        - asset: fonts/OpenSans/OpenSans-SemiBold.ttf
        - asset: fonts/OpenSans/OpenSans-Regular.ttf
          #weight: 700
scripts:
  build: flutter pub run build_runner build
  clean: flutter pub run build_runner clean