/// Flutter icons ElulIcons
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  ElulIcons
///      fonts:
///       - asset: fonts/ElulIcons.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class ElulIcons {
  ElulIcons._();

  static const _kFontFam = 'ElulIcons';
  static const _kFontPkg = null;

  static const IconData calendar_icon = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData menu_icon = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData routine_icon = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData add_icon = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData back_icon = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData backarrow_icon = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
